// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: policies/pb/policies.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PolicyID string `protobuf:"bytes,1,opt,name=policyID,proto3" json:"policyID,omitempty"`
	OwnerID  string `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
}

func (x *PolicyByIDReq) Reset() {
	*x = PolicyByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policies_pb_policies_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyByIDReq) ProtoMessage() {}

func (x *PolicyByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_policies_pb_policies_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyByIDReq.ProtoReflect.Descriptor instead.
func (*PolicyByIDReq) Descriptor() ([]byte, []int) {
	return file_policies_pb_policies_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyByIDReq) GetPolicyID() string {
	if x != nil {
		return x.PolicyID
	}
	return ""
}

func (x *PolicyByIDReq) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type PolicyByGroupsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupIDs []string `protobuf:"bytes,1,rep,name=groupIDs,proto3" json:"groupIDs,omitempty"`
}

func (x *PolicyByGroupsReq) Reset() {
	*x = PolicyByGroupsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policies_pb_policies_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyByGroupsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyByGroupsReq) ProtoMessage() {}

func (x *PolicyByGroupsReq) ProtoReflect() protoreflect.Message {
	mi := &file_policies_pb_policies_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyByGroupsReq.ProtoReflect.Descriptor instead.
func (*PolicyByGroupsReq) Descriptor() ([]byte, []int) {
	return file_policies_pb_policies_proto_rawDescGZIP(), []int{1}
}

func (x *PolicyByGroupsReq) GetGroupIDs() []string {
	if x != nil {
		return x.GroupIDs
	}
	return nil
}

type PolicyDataRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Backend string `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Version int32  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	Data    []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PolicyDataRes) Reset() {
	*x = PolicyDataRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policies_pb_policies_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyDataRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDataRes) ProtoMessage() {}

func (x *PolicyDataRes) ProtoReflect() protoreflect.Message {
	mi := &file_policies_pb_policies_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDataRes.ProtoReflect.Descriptor instead.
func (*PolicyDataRes) Descriptor() ([]byte, []int) {
	return file_policies_pb_policies_proto_rawDescGZIP(), []int{2}
}

func (x *PolicyDataRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PolicyDataRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyDataRes) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *PolicyDataRes) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PolicyDataRes) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PolicyDataListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Policies []*PolicyDataRes `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
}

func (x *PolicyDataListRes) Reset() {
	*x = PolicyDataListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_policies_pb_policies_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PolicyDataListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyDataListRes) ProtoMessage() {}

func (x *PolicyDataListRes) ProtoReflect() protoreflect.Message {
	mi := &file_policies_pb_policies_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyDataListRes.ProtoReflect.Descriptor instead.
func (*PolicyDataListRes) Descriptor() ([]byte, []int) {
	return file_policies_pb_policies_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyDataListRes) GetPolicies() []*PolicyDataRes {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_policies_pb_policies_proto protoreflect.FileDescriptor

var file_policies_pb_policies_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6f,
	0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x22, 0x45, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x2f, 0x0a,
	0x11, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x73, 0x22, 0x7b,
	0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x11, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x33, 0x0a, 0x08, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x52, 0x08, 0x70, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x65, 0x73, 0x32, 0xb3, 0x01, 0x0a, 0x0d, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x17, 0x2e,
	0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65,
	0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x58, 0x0a, 0x1a, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x44, 0x61, 0x74, 0x61, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12,
	0x1b, 0x2e, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63,
	0x79, 0x42, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x70,
	0x6f, 0x6c, 0x69, 0x63, 0x69, 0x65, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_policies_pb_policies_proto_rawDescOnce sync.Once
	file_policies_pb_policies_proto_rawDescData = file_policies_pb_policies_proto_rawDesc
)

func file_policies_pb_policies_proto_rawDescGZIP() []byte {
	file_policies_pb_policies_proto_rawDescOnce.Do(func() {
		file_policies_pb_policies_proto_rawDescData = protoimpl.X.CompressGZIP(file_policies_pb_policies_proto_rawDescData)
	})
	return file_policies_pb_policies_proto_rawDescData
}

var file_policies_pb_policies_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_policies_pb_policies_proto_goTypes = []interface{}{
	(*PolicyByIDReq)(nil),     // 0: policies.PolicyByIDReq
	(*PolicyByGroupsReq)(nil), // 1: policies.PolicyByGroupsReq
	(*PolicyDataRes)(nil),     // 2: policies.PolicyDataRes
	(*PolicyDataListRes)(nil), // 3: policies.PolicyDataListRes
}
var file_policies_pb_policies_proto_depIdxs = []int32{
	2, // 0: policies.PolicyDataListRes.policies:type_name -> policies.PolicyDataRes
	0, // 1: policies.PolicyService.RetrievePolicyData:input_type -> policies.PolicyByIDReq
	1, // 2: policies.PolicyService.RetrievePolicyDataByGroups:input_type -> policies.PolicyByGroupsReq
	2, // 3: policies.PolicyService.RetrievePolicyData:output_type -> policies.PolicyDataRes
	3, // 4: policies.PolicyService.RetrievePolicyDataByGroups:output_type -> policies.PolicyDataListRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_policies_pb_policies_proto_init() }
func file_policies_pb_policies_proto_init() {
	if File_policies_pb_policies_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_policies_pb_policies_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policies_pb_policies_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyByGroupsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policies_pb_policies_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyDataRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_policies_pb_policies_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PolicyDataListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_policies_pb_policies_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policies_pb_policies_proto_goTypes,
		DependencyIndexes: file_policies_pb_policies_proto_depIdxs,
		MessageInfos:      file_policies_pb_policies_proto_msgTypes,
	}.Build()
	File_policies_pb_policies_proto = out.File
	file_policies_pb_policies_proto_rawDesc = nil
	file_policies_pb_policies_proto_goTypes = nil
	file_policies_pb_policies_proto_depIdxs = nil
}
