# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-policies
spec:
  replicas: {{ .Values.defaults.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: policies
  template:
    metadata:
      annotations:
        commit_sha: {{ .Values.defaults.image.commitHash }}
      labels:
        app: {{ .Release.Name }}
        component: policies
    spec:
      containers:
        - env:
            - name: MF_JAEGER_URL
              value:
                {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            - name: ORB_POLICIES_DB
              value: {{ index .Values "postgresql-policies" "postgresqlDatabase" }}
            - name: ORB_POLICIES_DB_HOST
              value: {{ .Release.Name }}-postgresql-policies
            - name: ORB_POLICIES_DB_PASS
              value: {{ index .Values "postgresql-policies" "postgresqlPassword" }}
            - name: ORB_POLICIES_DB_PORT
              value: "{{ .Values.policies.dbPort }}"
            - name: ORB_POLICIES_DB_SSL_MODE
              value: "{{ .Values.policies.dbSSL }}"
            - name: ORB_POLICIES_DB_USER
              value: {{ index .Values "postgresql-policies" "postgresqlUsername" }}
            - name: ORB_POLICIES_ES_URL
              value:
                {{ .Release.Name }}-redis-streams-master:{{ .Values.policies.redisESPort }}
            - name: ORB_POLICIES_HTTP_PORT
              value: "{{ .Values.policies.httpPort }}"
            - name: ORB_POLICIES_GRPC_PORT
              value: "{{ .Values.policies.grpcPort }}"
            - name: ORB_POLICIES_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.policies.logLevel }}
            - name: MF_AUTH_GRPC_URL
              value:
                {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
          image: "{{ default .Values.defaults.image.repository }}/orb-policies:{{ default .Values.defaults.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.policies.image.pullPolicy }}
          name: {{ .Release.Name }}-policies
          ports:
            - containerPort: {{ .Values.policies.httpPort }}
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
