# Copyright (c) Mainflux
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-users-config
data:
  email.tmpl: |
    To: {{.To}}
    From: {{.From}}
    Subject: {{.Subject}}
    {{.Header}}
    You have initiated password reset.
    Follow the link below to reset password.
    {{.Content}}
  {{.Footer}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-users
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: users
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: users
    spec:
      containers:
        - env:
            - name: MF_JAEGER_URL
              value:
                {{ .Release.Name }}-jaeger-operator-jaeger-agent:{{ .Values.defaults.jaegerPort }}
            - name: MF_USERS_DB
              value: {{ index .Values "postgresql-users"  "postgresqlDatabase" }}
            - name: MF_USERS_DB_HOST
              value: {{ .Release.Name }}-postgresql-users
            - name: MF_USERS_DB_PASS
              value: {{ index .Values "postgresql-users" "postgresqlPassword" }}
            - name: MF_USERS_DB_PORT
              value: "{{ .Values.users.dbPort }}"
            - name: MF_USERS_DB_USER
              value: {{ index .Values "postgresql-users" "postgresqlUsername" }}
            - name: MF_USERS_HTTP_PORT
              value: "{{ .Values.users.httpPort }}"
            - name: MF_USERS_LOG_LEVEL
              value: {{ default .Values.defaults.logLevel .Values.users.logLevel }}
            - name: MF_AUTH_GRPC_URL
              value:
                {{ .Release.Name }}-envoy:{{ .Values.auth.grpcPort }}
            - name: MF_TOKEN_RESET_ENDPOINT
              value: "#/auth/reset-password"
            - name: MF_USERS_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.users.admin.secretName }}
                  key: {{ .Values.users.admin.emailSecretKey }}
            - name: MF_USERS_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.users.admin.secretName }}
                  key: {{ .Values.users.admin.passwordSecretKey }}
          image: "{{ default .Values.defaults.image.mfRepository .Values.users.image.repository }}/users:{{ default .Values.defaults.image.mfTag .Values.users.image.tag }}"
          imagePullPolicy: {{ default .Values.defaults.image.pullPolicy .Values.users.image.pullPolicy }}
          name: {{ .Release.Name }}-users
          ports:
            - containerPort: {{ .Values.users.httpPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /email.tmpl
              name: users-config
              subPath: email.tmpl
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - configMap:
            defaultMode: 256
            name: {{ .Release.Name }}-users-config
            optional: false
          name: users-config
