// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: sinks/pb/sinks.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SinksRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sinks []*SinkRes `protobuf:"bytes,1,rep,name=sinks,proto3" json:"sinks,omitempty"`
}

func (x *SinksRes) Reset() {
	*x = SinksRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinks_pb_sinks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SinksRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinksRes) ProtoMessage() {}

func (x *SinksRes) ProtoReflect() protoreflect.Message {
	mi := &file_sinks_pb_sinks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinksRes.ProtoReflect.Descriptor instead.
func (*SinksRes) Descriptor() ([]byte, []int) {
	return file_sinks_pb_sinks_proto_rawDescGZIP(), []int{0}
}

func (x *SinksRes) GetSinks() []*SinkRes {
	if x != nil {
		return x.Sinks
	}
	return nil
}

type SinksFilterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OtelEnabled string `protobuf:"bytes,1,opt,name=otelEnabled,proto3" json:"otelEnabled,omitempty"`
	State       string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *SinksFilterReq) Reset() {
	*x = SinksFilterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinks_pb_sinks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SinksFilterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinksFilterReq) ProtoMessage() {}

func (x *SinksFilterReq) ProtoReflect() protoreflect.Message {
	mi := &file_sinks_pb_sinks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinksFilterReq.ProtoReflect.Descriptor instead.
func (*SinksFilterReq) Descriptor() ([]byte, []int) {
	return file_sinks_pb_sinks_proto_rawDescGZIP(), []int{1}
}

func (x *SinksFilterReq) GetOtelEnabled() string {
	if x != nil {
		return x.OtelEnabled
	}
	return ""
}

func (x *SinksFilterReq) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type SinkByIDReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SinkID  string `protobuf:"bytes,1,opt,name=sinkID,proto3" json:"sinkID,omitempty"`
	OwnerID string `protobuf:"bytes,2,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
}

func (x *SinkByIDReq) Reset() {
	*x = SinkByIDReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinks_pb_sinks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SinkByIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkByIDReq) ProtoMessage() {}

func (x *SinkByIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_sinks_pb_sinks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkByIDReq.ProtoReflect.Descriptor instead.
func (*SinkByIDReq) Descriptor() ([]byte, []int) {
	return file_sinks_pb_sinks_proto_rawDescGZIP(), []int{2}
}

func (x *SinkByIDReq) GetSinkID() string {
	if x != nil {
		return x.SinkID
	}
	return ""
}

func (x *SinkByIDReq) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type SinkRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags        []byte `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	State       string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Error       string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Backend     string `protobuf:"bytes,7,opt,name=backend,proto3" json:"backend,omitempty"`
	Config      []byte `protobuf:"bytes,8,opt,name=config,proto3" json:"config,omitempty"`
	OwnerID     string `protobuf:"bytes,9,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
}

func (x *SinkRes) Reset() {
	*x = SinkRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sinks_pb_sinks_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SinkRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinkRes) ProtoMessage() {}

func (x *SinkRes) ProtoReflect() protoreflect.Message {
	mi := &file_sinks_pb_sinks_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinkRes.ProtoReflect.Descriptor instead.
func (*SinkRes) Descriptor() ([]byte, []int) {
	return file_sinks_pb_sinks_proto_rawDescGZIP(), []int{3}
}

func (x *SinkRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SinkRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SinkRes) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SinkRes) GetTags() []byte {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SinkRes) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SinkRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SinkRes) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *SinkRes) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SinkRes) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

var File_sinks_pb_sinks_proto protoreflect.FileDescriptor

var file_sinks_pb_sinks_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x69, 0x6e, 0x6b, 0x73, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x69, 0x6e, 0x6b, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x69, 0x6e, 0x6b, 0x73, 0x22, 0x30, 0x0a,
	0x08, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x12, 0x24, 0x0a, 0x05, 0x73, 0x69, 0x6e,
	0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x6e, 0x6b, 0x73,
	0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x52, 0x05, 0x73, 0x69, 0x6e, 0x6b, 0x73, 0x22,
	0x48, 0x0a, 0x0e, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x20, 0x0a, 0x0b, 0x6f, 0x74, 0x65, 0x6c, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x74, 0x65, 0x6c, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x69, 0x6e,
	0x6b, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x6e, 0x6b,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x69, 0x6e, 0x6b, 0x49, 0x44,
	0x12, 0x18, 0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0xdb, 0x01, 0x0a, 0x07, 0x53,
	0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x61, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x32, 0x7e, 0x0a, 0x0b, 0x53, 0x69, 0x6e, 0x6b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x52, 0x65, 0x74, 0x72, 0x69,
	0x65, 0x76, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x12, 0x12, 0x2e, 0x73, 0x69, 0x6e, 0x6b, 0x73, 0x2e,
	0x53, 0x69, 0x6e, 0x6b, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x73, 0x69,
	0x6e, 0x6b, 0x73, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x0d, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x15,
	0x2e, 0x73, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x53, 0x69, 0x6e, 0x6b, 0x73, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x73, 0x69, 0x6e, 0x6b, 0x73, 0x2e, 0x53, 0x69,
	0x6e, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x73, 0x69, 0x6e, 0x6b,
	0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sinks_pb_sinks_proto_rawDescOnce sync.Once
	file_sinks_pb_sinks_proto_rawDescData = file_sinks_pb_sinks_proto_rawDesc
)

func file_sinks_pb_sinks_proto_rawDescGZIP() []byte {
	file_sinks_pb_sinks_proto_rawDescOnce.Do(func() {
		file_sinks_pb_sinks_proto_rawDescData = protoimpl.X.CompressGZIP(file_sinks_pb_sinks_proto_rawDescData)
	})
	return file_sinks_pb_sinks_proto_rawDescData
}

var file_sinks_pb_sinks_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_sinks_pb_sinks_proto_goTypes = []interface{}{
	(*SinksRes)(nil),       // 0: sinks.SinksRes
	(*SinksFilterReq)(nil), // 1: sinks.SinksFilterReq
	(*SinkByIDReq)(nil),    // 2: sinks.SinkByIDReq
	(*SinkRes)(nil),        // 3: sinks.SinkRes
}
var file_sinks_pb_sinks_proto_depIdxs = []int32{
	3, // 0: sinks.SinksRes.sinks:type_name -> sinks.SinkRes
	2, // 1: sinks.SinkService.RetrieveSink:input_type -> sinks.SinkByIDReq
	1, // 2: sinks.SinkService.RetrieveSinks:input_type -> sinks.SinksFilterReq
	3, // 3: sinks.SinkService.RetrieveSink:output_type -> sinks.SinkRes
	0, // 4: sinks.SinkService.RetrieveSinks:output_type -> sinks.SinksRes
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sinks_pb_sinks_proto_init() }
func file_sinks_pb_sinks_proto_init() {
	if File_sinks_pb_sinks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sinks_pb_sinks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SinksRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sinks_pb_sinks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SinksFilterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sinks_pb_sinks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SinkByIDReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sinks_pb_sinks_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SinkRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sinks_pb_sinks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sinks_pb_sinks_proto_goTypes,
		DependencyIndexes: file_sinks_pb_sinks_proto_depIdxs,
		MessageInfos:      file_sinks_pb_sinks_proto_msgTypes,
	}.Build()
	File_sinks_pb_sinks_proto = out.File
	file_sinks_pb_sinks_proto_rawDesc = nil
	file_sinks_pb_sinks_proto_goTypes = nil
	file_sinks_pb_sinks_proto_depIdxs = nil
}
