ARG ORB_TAG=develop
ARG PKTVISOR_TAG=develop
ARG OTEL_TAG=0.91.0

FROM orbcommunity/orb-agent:${ORB_TAG} AS orb

FROM otel/opentelemetry-collector-contrib:${OTEL_TAG} AS otelcol-contrib

FROM orbcommunity/pktvisor:${PKTVISOR_TAG}

# adding orb-agent
RUN mkdir /opt/orb
COPY --from=orb /usr/local/bin/orb-agent /usr/local/bin/orb-agent
COPY ./agent/docker/agent_default_full.yaml /opt/orb/agent_default.yaml
COPY --from=orb /usr/local/bin/orb-agent-entry.sh /usr/local/bin/orb-agent-entry.sh
COPY --from=orb /run-agent.sh /run-agent.sh

COPY --from=otelcol-contrib /otelcol-contrib /usr/local/bin/otelcol-contrib

RUN chmod a+x /run-agent.sh

ENTRYPOINT [ "/usr/local/bin/orb-agent-entry.sh" ]
